import styles from './styles.module.css'
import Head from 'next/head'
import { PropsWithChildren } from 'react'

export type PageHeadTemplateProps = {
  title: string
}

export function MainTemplate({
  title,
  children
}: PropsWithChildren<PageHeadTemplateProps>) {
  return (
    <>
      <Head>
        <title>ShoppingCart - {title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main_container}>{children}</main>
    </>
  )
}
